---
title: "calc_gw_recharge"
author: "Steffen Ehrmann"
date: "11/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This scripts calculates the groundwater recharge on a monthly basis.

```{r, load packages}
root <- "/home/se87kuhe/Nextcloud/geohack19"
```

```{r, load packages}
library(raster)
```

# Process data

We read in data for each month, calculate the recharge value that has accumulated in that month and summarise it over all months, to get the value of new groundwater that has accumulated in that year.

```{r load data}
for(i in 1:12){
  # read in all layers, per month
  aet <- raster(x = paste0(root, "/data/raster/agg_terraclimate_aet_1958_CurrentYear_GLOBE.nc"), band = i)
  ppt <- raster(x = paste0(root, "/data/raster/agg_terraclimate_ppt_1958_CurrentYear_GLOBE.nc"), band = i)
  q <- raster(x = paste0(root, "/data/raster/agg_terraclimate_q_1958_CurrentYear_GLOBE.nc"), band = i)
  
  # calculate tentative value of recharge
  temp <- ppt - aet - q
  
  # summarise recharge over all months, because we want to know how much water is being accumulated per pixel
  if(i == 1){
    recharge <- temp
  } else {
    recharge <- recharge + temp
  }
}

# write the raster
writeRaster(x = recharge, filename = paste0(root, "/data/output/recharge_sum_2015.tif"), options=c("COMPRESS=LZW"))
```

